server:
  port: 8080

#--------------------------------------------------------------------#
spring:
  profiles:
    active: ${PROFILE:local}
  application:
    name: livraria

#---------------------------------------------------------------------#
management:
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true